import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service | PostForge',
};

export default function TermsPage() {
  return (
    <div className="legal">
      <header className="legal-header">
        <Link href="/" className="legal-back">← Back to PostForge</Link>
      </header>

      <main className="legal-main">
        <h1>Terms of Service</h1>
        <p className="legal-date">Last updated: January 13, 2025</p>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By using TweetForge, you agree to these Terms of Service. If you don't agree, 
          please don't use the service.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          PostForge is an AI-powered post generator that helps you create and publish 
          posts to X. The service requires X OAuth authentication.
        </p>

        <h2>3. User Accounts</h2>
        <p>By connecting your X account, you authorize us to:</p>
        <ul>
          <li>Access your basic profile information</li>
          <li>Publish posts on your behalf when you click "Post to X"</li>
        </ul>
        <p>You're responsible for all activity under your account.</p>

        <h2>4. AI-Generated Content</h2>
        <p>
          Posts generated by PostForge are AI suggestions. You are responsible for 
          reviewing and editing content before posting. You assume full responsibility 
          for any content you post to X.
        </p>

        <h2>5. Prohibited Uses</h2>
        <p>Don't use PostForge to:</p>
        <ul>
          <li>Generate spam, misleading, or harmful content</li>
          <li>Harass or abuse others</li>
          <li>Violate X's Terms of Service</li>
          <li>Generate illegal content</li>
        </ul>

        <h2>6. Limitation of Liability</h2>
        <p>
          PostForge is provided "as is" without warranties. We're not liable for any 
          damages from using the service, including actions taken by X on your account.
        </p>

        <h2>7. Changes</h2>
        <p>We may update these terms. Continued use means you accept changes.</p>
      </main>

      <footer className="legal-footer">© 2025 PostForge</footer>
    </div>
  );
}
